
// https://ns.editeur.org/onix/en/83 
export enum BibleVersion {
  ALV = 'ALV', // Alberto Vaccari
  AMP = 'AMP', // Amplified
  ANM = 'ANM', // Antonio Martini
  ASV = 'ASV', // American Standard
  BLA = 'BLA', // Biblia de las Americas
  BLB = 'BLB', // Nueva Biblia de las Americas
  CEB = 'CEB', // Common English Bible
  CEI = 'CEI', // Conferenza Episcopale Italiana
  CEN = 'CEN', // Conferenza Episcopale Italiana 2008
  CEV = 'CEV', // Contemporary English
  CNC = 'CNC', // Concordata
  DDI = 'DDI', // Diodati
  DDN = 'DDN', // Nuova Diodati
  DOU = 'DOU', // Douay-Rheims
  EIN = 'EIN', // Einheitsübersetzung
  ESV = 'ESV', // English Standard
  FBB = 'FBB', // Biblia (1776)
  FRA = 'FRA', // Raamattu (1933/1938)
  FRK = 'FRK', // Raamattu kansalle
  FRM = 'FRM', // Raamattu (1992)
  GDW = 'GDW', // God’s Word
  GEN = 'GEN', // Geneva
  GNB = 'GNB', // Good News
  GPR = 'GPR', // Galbiati, Penna, Rossano – UTET
  GRK = 'GRK', // Original Greek
  GRM = 'GRM', // Garofano, Rinaldi – Marietti
  HBR = 'HBR', // Original Hebrew
  HCS = 'HCS', // Holman Christian Standard
  ICB = 'ICB', // International Children’s
  ILC = 'ILC', // Traduzione Interconfessionale in Lingua Corrente
  JER = 'JER', // Jerusalem
  KJV = 'KJV', // King James
  KJT = 'KJT', // 21st Century King James
  LVB = 'LVB', // Living Bible
  LZZ = 'LZZ', // Luzzi
  MSG = 'MSG', // Message Bible
  NAB = 'NAB', // New American
  NAS = 'NAS', // New American Standard
  NAU = 'NAU', // New American Standard, Updated
  NBA = 'NBA', // Bibelen 1895
  NBB = 'NBB', // Bibelen 1930
  NBC = 'NBC', // Bibelen 1938
  NBD = 'NBD', // Bibelen 1978-85
  NBE = 'NBE', // Bibelen 1978
  NBF = 'NBF', // Bibelen 1985
  NBG = 'NBG', // Norsk Bibel 88
  NBH = 'NBH', // Bibelen 1978-85/rev. 2005
  NBI = 'NBI', // Bibelen 2011
  NBJ = 'NBJ', // Norsk Bibel 88/rev. 2007
  NBK = 'NBK', // Fauskanger 2015
  NBL = 'NBL', // Bibelen 2011/rev. 2024
  NBP = 'NBP', // Pollestad 2023
  NCV = 'NCV', // New Century
  NEB = 'NEB', // New English
  NGO = 'NGO', // Bibelen Guds ord
  NIV = 'NIV', // New International
  NIR = 'NIR', // New International Reader’s
  NJB = 'NJB', // New Jerusalem
  NKJ = 'NKJ', // New King James
  NNK = 'NNK', // Bibelen, nynorsk
  NLV = 'NLV', // New Living
  NRS = 'NRS', // New Revised Standard
  NTV = 'NTV', // Nueva Traducción Viviente
  NVB = 'NVB', // Novissima Versione della Bibbia
  NVD = 'NVD', // Nueva Biblia al Dia
  NVI = 'NVI', // Nueva Version Internacional
  PHP = 'PHP', // New Testament in Modern English (Phillips)
  REB = 'REB', // Revised English
  REV = 'REV', // Revised Version
  RSV = 'RSV', // Revised Standard
  RVL = 'RVL', // Reina Valera
  SBB = 'SBB', // Bibel 2000
  SMK = 'SMK', // Bibelen, samisk
  TEV = 'TEV', // Today’s English
  TNI = 'TNI', // Today’s New International
  ZZZ = 'ZZZ', // Other
}