
// https://ns.editeur.org/onix/en/96 
export enum CurrencyCodeBasedOnIso4217 {
  AED = 'AED', // UAE Dirham
  AFA = 'AFA', // Afghani
  AFN = 'AFN', // Afghani
  ALL = 'ALL', // Lek
  AMD = 'AMD', // Armenian Dram
  ANG = 'ANG', // Netherlands Antillian Guilder
  AOA = 'AOA', // Kwanza
  ARS = 'ARS', // Argentine Peso
  ATS = 'ATS', // Schilling
  AUD = 'AUD', // Australian Dollar
  AWG = 'AWG', // Aruban Florin
  AZN = 'AZN', // Azerbaijan Manat
  BAM = 'BAM', // Convertible Marks
  BBD = 'BBD', // Barbados Dollar
  BDT = 'BDT', // Taka
  BEF = 'BEF', // Belgian Franc
  BGL = 'BGL', // Bulgarian Lev
  BGN = 'BGN', // Bulgarian Lev
  BHD = 'BHD', // Bahraini Dinar
  BIF = 'BIF', // Burundi Franc
  BMD = 'BMD', // Bermudian Dollar
  BND = 'BND', // Brunei Dollar
  BOB = 'BOB', // Boliviano
  BRL = 'BRL', // Brazilian Real
  BSD = 'BSD', // Bahamian Dollar
  BTN = 'BTN', // Ngultrun
  BWP = 'BWP', // Pula
  BYR = 'BYR', // (Old) Belarussian Ruble
  BYN = 'BYN', // Belarussian Ruble
  BZD = 'BZD', // Belize Dollar
  CAD = 'CAD', // Canadian Dollar
  CDF = 'CDF', // Franc Congolais
  CHF = 'CHF', // Swiss Franc
  CLP = 'CLP', // Chilean Peso
  CNY = 'CNY', // Yuan Renminbi
  COP = 'COP', // Colombian Peso
  CRC = 'CRC', // Costa Rican Colon
  CSD = 'CSD', // Serbian Dinar
  CUC = 'CUC', // Cuban Convertible Peso
  CUP = 'CUP', // Cuban Peso
  CVE = 'CVE', // Cabo Verde Escudo
  CYP = 'CYP', // Cyprus Pound
  CZK = 'CZK', // Czech Koruna
  DEM = 'DEM', // Mark
  DJF = 'DJF', // Djibouti Franc
  DKK = 'DKK', // Danish Krone
  DOP = 'DOP', // Dominican Peso
  DZD = 'DZD', // Algerian Dinar
  EEK = 'EEK', // Kroon
  EGP = 'EGP', // Egyptian Pound
  ERN = 'ERN', // Nakfa
  ESP = 'ESP', // Peseta
  ETB = 'ETB', // Ethiopian Birr
  EUR = 'EUR', // Euro
  FIM = 'FIM', // Markka
  FJD = 'FJD', // Fiji Dollar
  FKP = 'FKP', // Falkland Islands Pound
  FRF = 'FRF', // Franc
  GBP = 'GBP', // Pound Sterling
  GEL = 'GEL', // Lari
  GHC = 'GHC', // Ghana Cedi
  GHS = 'GHS', // Ghana Cedi
  GIP = 'GIP', // Gibraltar Pound
  GMD = 'GMD', // Dalasi
  GNF = 'GNF', // Guinean Franc
  GRD = 'GRD', // Drachma
  GTQ = 'GTQ', // Quetzal
  GWP = 'GWP', // Guinea-Bissau Peso
  GYD = 'GYD', // Guyana Dollar
  HKD = 'HKD', // Hong Kong Dollar
  HNL = 'HNL', // Lempira
  HRK = 'HRK', // Kuna
  HTG = 'HTG', // Gourde
  HUF = 'HUF', // Forint
  IDR = 'IDR', // Rupiah
  IEP = 'IEP', // Punt
  ILS = 'ILS', // New Israeli Sheqel
  INR = 'INR', // Indian Rupee
  IQD = 'IQD', // Iraqi Dinar
  IRR = 'IRR', // Iranian Rial
  ISK = 'ISK', // Iceland Krona
  ITL = 'ITL', // Lira
  JMD = 'JMD', // Jamaican Dollar
  JOD = 'JOD', // Jordanian Dinar
  JPY = 'JPY', // Yen
  KES = 'KES', // Kenyan Shilling
  KGS = 'KGS', // Som
  KHR = 'KHR', // Riel
  KMF = 'KMF', // Comorian Franc
  KPW = 'KPW', // North Korean Won
  KRW = 'KRW', // Won
  KWD = 'KWD', // Kuwaiti Dinar
  KYD = 'KYD', // Cayman Islands Dollar
  KZT = 'KZT', // Tenge
  LAK = 'LAK', // Lao Kip
  LBP = 'LBP', // Lebanese Pound
  LKR = 'LKR', // Sri Lanka Rupee
  LRD = 'LRD', // Liberian Dollar
  LSL = 'LSL', // Loti
  LTL = 'LTL', // Litus
  LUF = 'LUF', // Luxembourg Franc
  LVL = 'LVL', // Latvian Lats
  LYD = 'LYD', // Libyan Dinar
  MAD = 'MAD', // Moroccan Dirham
  MDL = 'MDL', // Moldovan Leu
  MGA = 'MGA', // Malagasy Ariary
  MGF = 'MGF', // Malagasy Franc
  MKD = 'MKD', // Denar
  MMK = 'MMK', // Kyat
  MNT = 'MNT', // Tugrik
  MOP = 'MOP', // Pataca
  MRO = 'MRO', // (Old) Ouguiya
  MRU = 'MRU', // Ouguiya
  MTL = 'MTL', // Maltese Lira
  MUR = 'MUR', // Mauritius Rupee
  MVR = 'MVR', // Rufiyaa
  MWK = 'MWK', // Malawi Kwacha
  MXN = 'MXN', // Mexican Peso
  MYR = 'MYR', // Malaysian Ringgit
  MZN = 'MZN', // Mozambique Metical
  NAD = 'NAD', // Namibia Dollar
  NGN = 'NGN', // Naira
  NIO = 'NIO', // Cordoba Oro
  NLG = 'NLG', // Guilder
  NOK = 'NOK', // Norwegian Krone
  NPR = 'NPR', // Nepalese Rupee
  NZD = 'NZD', // New Zealand Dollar
  OMR = 'OMR', // Rial Omani
  PAB = 'PAB', // Balboa
  PEN = 'PEN', // Sol
  PGK = 'PGK', // Kina
  PHP = 'PHP', // Philippine Peso
  PKR = 'PKR', // Pakistan Rupee
  PLN = 'PLN', // Złoty
  PTE = 'PTE', // Escudo
  PYG = 'PYG', // Guarani
  QAR = 'QAR', // Qatari Rial
  ROL = 'ROL', // Romanian Old Leu
  RON = 'RON', // Romanian Leu
  RSD = 'RSD', // Serbian Dinar
  RUB = 'RUB', // Russian Ruble
  RUR = 'RUR', // Russian Ruble
  RWF = 'RWF', // Rwanda Franc
  SAR = 'SAR', // Saudi Riyal
  SBD = 'SBD', // Solomon Islands Dollar
  SCR = 'SCR', // Seychelles Rupee
  SDD = 'SDD', // Sudanese Dinar
  SDG = 'SDG', // Sudanese Pound
  SEK = 'SEK', // Swedish Krona
  SGD = 'SGD', // Singapore Dollar
  SHP = 'SHP', // Saint Helena Pound
  SIT = 'SIT', // Tolar
  SKK = 'SKK', // Slovak Koruna
  SLE = 'SLE', // Leone
  SLL = 'SLL', // Leone
  SOS = 'SOS', // Somali Shilling
  SRD = 'SRD', // Surinam Dollar
  SRG = 'SRG', // Suriname Guilder
  STD = 'STD', // (Old) Dobra
  STN = 'STN', // Dobra
  SVC = 'SVC', // El Salvador Colon
  SYP = 'SYP', // Syrian Pound
  SZL = 'SZL', // Lilangeni
  THB = 'THB', // Baht
  TJS = 'TJS', // Somoni
  TMM = 'TMM', // Turkmenistan Manat
  TMT = 'TMT', // Turkmenistan New Manat
  TND = 'TND', // Tunisian Dinar
  TOP = 'TOP', // Pa’anga
  TPE = 'TPE', // Timor Escudo
  TRL = 'TRL', // Turkish Lira (old)
  TRY = 'TRY', // Turkish Lira
  TTD = 'TTD', // Trinidad and Tobago Dollar
  TWD = 'TWD', // New Taiwan Dollar
  TZS = 'TZS', // Tanzanian Shilling
  UAH = 'UAH', // Hryvnia
  UGX = 'UGX', // Uganda Shilling
  USD = 'USD', // US Dollar
  UYU = 'UYU', // Peso Uruguayo
  UZS = 'UZS', // Uzbekistan Sum
  VEB = 'VEB', // Bolívar
  VEF = 'VEF', // Bolívar
  VES = 'VES', // Bolívar Soberano
  VND = 'VND', // Dong
  VUV = 'VUV', // Vatu
  WST = 'WST', // Tala
  XAF = 'XAF', // CFA Franc BEAC
  XCD = 'XCD', // East Caribbean Dollar
  XOF = 'XOF', // CFA Franc BCEAO
  XPF = 'XPF', // CFP Franc
  YER = 'YER', // Yemeni Rial
  YUM = 'YUM', // Yugoslavian Dinar
  ZAR = 'ZAR', // Rand
  ZMK = 'ZMK', // Kwacha
  ZMW = 'ZMW', // Zambian Kwacha
  ZWD = 'ZWD', // Zimbabwe Dollar
  ZWL = 'ZWL', // Zimbabwe Dollar
}