
// https://ns.editeur.org/onix/en/196 
export enum EpublicationAccessibilityDetails {
  _00 = '00', // Accessibility summary
  _01 = '01', // LIA Compliance Scheme
  _02 = '02', // EPUB Accessibility Specification 1.0 A
  _03 = '03', // EPUB Accessibility Specification 1.0 AA
  _04 = '04', // Epub Accessibility Specification 1.1
  _05 = '05', // PDF/UA
  _08 = '08', // Unknown accessibility
  _09 = '09', // Inaccessible, or known limited accessibility
  _10 = '10', // No reading system accessibility options actively disabled (except)
  _11 = '11', // Table of contents navigation
  _12 = '12', // Index navigation
  _13 = '13', // Single logical reading order
  _14 = '14', // Short alternative textual descriptions
  _15 = '15', // Full alternative textual descriptions
  _16 = '16', // Visualised data also available as non-graphical data
  _17 = '17', // Accessible math content as MathML
  _18 = '18', // Accessible chemistry content as ChemML
  _19 = '19', // Print-equivalent page numbering
  _20 = '20', // Synchronised pre-recorded audio
  _21 = '21', // Text-to-speech hinting provided
  _22 = '22', // Language tagging provided
  _24 = '24', // Dyslexia readability
  _25 = '25', // Use of color is not sole means of conveying information
  _26 = '26', // Use of high contrast between text and background color
  _27 = '27', // Use of high contrast between foreground and background audio
  _28 = '28', // Full alternative audio descriptions
  _29 = '29', // Next / Previous structural navigation
  _30 = '30', // ARIA roles provided
  _31 = '31', // Accessible controls provided
  _32 = '32', // Landmark navigation
  _34 = '34', // Accessible chemistry content (as MathML)
  _35 = '35', // Accessible math content (as LaTeX)
  _36 = '36', // All textual content can be modified
  _37 = '37', // Use of ultra-high contrast between text foreground and background
  _38 = '38', // Unusual words or abbreviations explained
  _39 = '39', // Supplementary material to an audiobook is accessible
  _40 = '40', // Link purposes clear
  _51 = '51', // All non-decorative content supports reading via pre-recorded audio
  _52 = '52', // All non-decorative content supports reading without sight
  _75 = '75', // EEA Exception 1 – Micro-enterprises
  _76 = '76', // EAA exception 2 – Disproportionate burden
  _77 = '77', // EAA exception 3 – Fundamental modification
  _80 = '80', // WCAG v2.0
  _81 = '81', // WCAG v2.1
  _82 = '82', // WCAG v2.2
  _84 = '84', // WCAG level A
  _85 = '85', // WCAG level AA
  _86 = '86', // WCAG level AAA
  _91 = '91', // Latest accessibility assessment date
  _92 = '92', // Accessibility addendum
  _93 = '93', // Compliance certification by
  _94 = '94', // Compliance web page for detailed accessibility information
  _95 = '95', // Trusted intermediary’s web page for detailed accessibility information
  _96 = '96', // Publisher’s web page for detailed accessibility information
  _97 = '97', // Compatibility tested
  _98 = '98', // Trusted Intermediary contact
  _99 = '99', // Publisher contact for further accessibility information
}