
// https://ns.editeur.org/onix/en/74 
export enum LanguageBasedOnIso6392b {
  abk = 'abk', // Abkhazian
  ace = 'ace', // Achinese
  ach = 'ach', // Acoli
  ada = 'ada', // Adangme
  ady = 'ady', // Adygei; Adyghe
  aar = 'aar', // Afar
  afh = 'afh', // Afrihili
  afr = 'afr', // Afrikaans
  afa = 'afa', // Afro-Asiatic languages
  ain = 'ain', // Ainu
  aka = 'aka', // Akan
  akk = 'akk', // Akkadian
  alb = 'alb', // Albanian
  ale = 'ale', // Aleut
  alg = 'alg', // Algonquian languages
  alq = 'alq', // Algonquin
  tut = 'tut', // Altaic languages
  amh = 'amh', // Amharic
  anp = 'anp', // Angika
  apa = 'apa', // Apache languages
  ara = 'ara', // Arabic
  arg = 'arg', // Aragonese
  qar = 'qar', // Aranés
  arp = 'arp', // Arapaho
  arw = 'arw', // Arawak
  arm = 'arm', // Armenian
  rup = 'rup', // Aromanian; Arumanian; Macedo-Romanian
  art = 'art', // Artificial languages
  asm = 'asm', // Assamese
  ast = 'ast', // Asturian; Bable; Leonese; Asturleonese
  ath = 'ath', // Athapascan languages
  atj = 'atj', // Atikamekw
  aus = 'aus', // Australian languages
  aav = 'aav', // Austro-Asiatic languages
  map = 'map', // Austronesian languages
  ava = 'ava', // Avaric
  ave = 'ave', // Avestan
  awa = 'awa', // Awadhi
  aym = 'aym', // Aymara
  aze = 'aze', // Azerbaijani
  ban = 'ban', // Balinese
  bat = 'bat', // Baltic languages
  bal = 'bal', // Baluchi
  bam = 'bam', // Bambara
  bai = 'bai', // Bamileke languages
  bad = 'bad', // Banda languages
  bnt = 'bnt', // Bantu languages
  bas = 'bas', // Basa
  bak = 'bak', // Bashkir
  baq = 'baq', // Basque
  btk = 'btk', // Batak languages
  bej = 'bej', // Beja; Bedawiyet
  bel = 'bel', // Belarusian
  bem = 'bem', // Bemba
  ben = 'ben', // Bengali
  ber = 'ber', // Berber languages
  bho = 'bho', // Bhojpuri
  bih = 'bih', // Bihari languages
  bik = 'bik', // Bikol
  bin = 'bin', // Bini; Edo
  bis = 'bis', // Bislama
  byn = 'byn', // Blin; Bilin
  zbl = 'zbl', // Blissymbols; Blissymbolics; Bliss
  brx = 'brx', // Bodo (India)
  bos = 'bos', // Bosnian
  bra = 'bra', // Braj
  bre = 'bre', // Breton
  bug = 'bug', // Buginese
  bul = 'bul', // Bulgarian
  bum = 'bum', // Bulu (Cameroon)
  bua = 'bua', // Buriat
  bur = 'bur', // Burmese
  cad = 'cad', // Caddo
  sro = 'sro', // Campidanese
  yue = 'yue', // Cantonese
  cat = 'cat', // Catalan
  cau = 'cau', // Caucasian languages
  cay = 'cay', // Cayuga
  ceb = 'ceb', // Cebuano
  cel = 'cel', // Celtic languages
  cai = 'cai', // Central American Indian languages
  tzm = 'tzm', // Central Atlas Tamazight
  khm = 'khm', // Central Khmer
  ckb = 'ckb', // Central Kurdish (Sorani)
  chg = 'chg', // Chagatai
  cmc = 'cmc', // Chamic languages
  cha = 'cha', // Chamorro
  che = 'che', // Chechen
  chr = 'chr', // Cherokee
  chy = 'chy', // Cheyenne
  chb = 'chb', // Chibcha
  nya = 'nya', // Chichewa; Chewa; Nyanja
  cic = 'cic', // Chickasaw
  chi = 'chi', // Chinese
  chn = 'chn', // Chinook jargon
  chp = 'chp', // Chipewyan; Dene Suline
  cho = 'cho', // Choctaw
  chu = 'chu', // Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic
  chk = 'chk', // Chuukese (Truk)
  chv = 'chv', // Chuvash
  nwc = 'nwc', // Classical Newari; Old Newari; Classical Nepal Bhasa
  syc = 'syc', // Classical Syriac
  cop = 'cop', // Coptic
  cor = 'cor', // Cornish
  cos = 'cos', // Corsican
  cre = 'cre', // Cree
  mus = 'mus', // Creek
  crp = 'crp', // Creoles and pidgins
  cpe = 'cpe', // Creoles and pidgins, English-based
  cpf = 'cpf', // Creoles and pidgins, French-based
  cpp = 'cpp', // Creoles and pidgins, Portuguese-based
  crh = 'crh', // Crimean Turkish; Crimean Tatar
  hrv = 'hrv', // Croatian
  scr = 'scr', // Croatian
  cus = 'cus', // Cushitic languages
  cze = 'cze', // Czech
  dak = 'dak', // Dakota
  dan = 'dan', // Danish
  dar = 'dar', // Dargwa
  prs = 'prs', // Dari; Afghan Persian
  del = 'del', // Delaware
  din = 'din', // Dinka
  div = 'div', // Divehi; Dhivehi; Maldivian
  doi = 'doi', // Dogri
  dgr = 'dgr', // Dogrib
  dra = 'dra', // Dravidian languages
  dua = 'dua', // Duala
  dum = 'dum', // Dutch, Middle (ca. 1050-1350)
  dut = 'dut', // Dutch; Flemish
  dyu = 'dyu', // Dyula
  dzo = 'dzo', // Dzongkha
  ike = 'ike', // Eastern Canadian Inuktitut
  frs = 'frs', // Eastern Frisian
  efi = 'efi', // Efik
  egy = 'egy', // Egyptian (Ancient)
  eka = 'eka', // Ekajuk
  elx = 'elx', // Elamite
  egl = 'egl', // Emilian
  eng = 'eng', // English
  enm = 'enm', // English, Middle (1100-1500)
  ang = 'ang', // English, Old (ca. 450-1100)
  myv = 'myv', // Erzya
  esx = 'esx', // Eskaleut languages
  epo = 'epo', // Esperanto
  est = 'est', // Estonian
  gez = 'gez', // Ethiopic (Ge’ez)
  ewe = 'ewe', // Ewe
  ewo = 'ewo', // Ewondo
  fan = 'fan', // Fang
  fat = 'fat', // Fanti
  fao = 'fao', // Faroese
  fij = 'fij', // Fijian
  fil = 'fil', // Filipino; Pilipino
  fin = 'fin', // Finnish
  fiu = 'fiu', // Finno-Ugrian languages
  fon = 'fon', // Fon
  fre = 'fre', // French
  frm = 'frm', // French, Middle (ca. 1400-1600)
  fro = 'fro', // French, Old (ca. 842-1400)
  fur = 'fur', // Friulian
  ful = 'ful', // Fulah
  gaa = 'gaa', // Gã
  car = 'car', // Galibi Carib
  glg = 'glg', // Galician
  qgl = 'qgl', // Gallo
  sdn = 'sdn', // Gallurese
  lug = 'lug', // Ganda
  grt = 'grt', // Garo
  gay = 'gay', // Gayo
  gba = 'gba', // Gbaya
  geo = 'geo', // Georgian
  ger = 'ger', // German
  gmh = 'gmh', // German, Middle High (ca. 1050-1500)
  goh = 'goh', // German, Old High (ca. 750-1050)
  gem = 'gem', // Germanic languages
  gil = 'gil', // Gilbertese
  git = 'git', // Gitxsan
  gon = 'gon', // Gondi
  gor = 'gor', // Gorontalo
  got = 'got', // Gothic
  grb = 'grb', // Grebo
  grc = 'grc', // Greek, Ancient (to 1453)
  gre = 'gre', // Greek, Modern (1453-)
  grn = 'grn', // Guarani
  nrf = 'nrf', // Guernésiais, Jèrriais
  guj = 'guj', // Gujarati
  gwi = 'gwi', // Gwich’in
  hai = 'hai', // Haida
  hat = 'hat', // Haitian; Haitian Creole
  hau = 'hau', // Hausa
  haw = 'haw', // Hawaiian
  heb = 'heb', // Hebrew
  her = 'her', // Herero
  hil = 'hil', // Hiligaynon
  him = 'him', // Himachali languages; Western Pahari languages
  hin = 'hin', // Hindi
  hmo = 'hmo', // Hiri Motu
  hit = 'hit', // Hittite
  hmx = 'hmx', // Hmong-Mien languages
  hmn = 'hmn', // Hmong; Mong
  hop = 'hop', // Hopi
  hun = 'hun', // Hungarian
  hup = 'hup', // Hupa
  iba = 'iba', // Iban
  ice = 'ice', // Icelandic
  ido = 'ido', // Ido
  ibo = 'ibo', // Igbo
  ijo = 'ijo', // Ijo languages
  ilo = 'ilo', // Iloko
  smn = 'smn', // Inari Sami
  inc = 'inc', // Indic languages
  ine = 'ine', // Indo-European languages
  ind = 'ind', // Indonesian
  inh = 'inh', // Ingush
  moe = 'moe', // Innu, Montagnais
  ina = 'ina', // Interlingua (International Auxiliary Language Association)
  ile = 'ile', // Interlingue; Occidental
  ikt = 'ikt', // Inuinnaqtun
  iku = 'iku', // Inuktitut
  ipk = 'ipk', // Inupiaq
  qiv = 'qiv', // Inuvialuktun
  ira = 'ira', // Iranian languages
  pes = 'pes', // Iranian Persian; Parsi
  gle = 'gle', // Irish
  mga = 'mga', // Irish, Middle (ca. 1100-1550)
  sga = 'sga', // Irish, Old (to 1100)
  iro = 'iro', // Iroquoian languages
  ita = 'ita', // Italian
  jpn = 'jpn', // Japanese
  jpx = 'jpx', // Japanese languages
  jav = 'jav', // Javanese
  jow = 'jow', // Jowulu
  jrb = 'jrb', // Judeo-Arabic
  jpr = 'jpr', // Judeo-Persian
  kbd = 'kbd', // Kabardian
  kbp = 'kbp', // Kabiyè
  kab = 'kab', // Kabyle
  kac = 'kac', // Kachin; Jingpho
  kal = 'kal', // Kalâtdlisut; Greenlandic
  xal = 'xal', // Kalmyk; Oirat
  kam = 'kam', // Kamba
  kan = 'kan', // Kannada
  kau = 'kau', // Kanuri
  kaa = 'kaa', // Kara-Kalpak
  krc = 'krc', // Karachay-Balkar
  kdr = 'kdr', // Karaim
  krl = 'krl', // Karelian
  kar = 'kar', // Karen languages
  kas = 'kas', // Kashmiri
  csb = 'csb', // Kashubian
  kaw = 'kaw', // Kawi
  kaz = 'kaz', // Kazakh
  kha = 'kha', // Khasi
  khi = 'khi', // Khoisan languages
  kho = 'kho', // Khotanese; Sakan
  xuu = 'xuu', // Khwedam, Kxoe
  kik = 'kik', // Kikuyu; Gikuyu
  kmb = 'kmb', // Kimbundu
  kin = 'kin', // Kinyarwanda
  kir = 'kir', // Kirghiz; Kyrgyz
  kqs = 'kqs', // Kissi, Northern
  kss = 'kss', // Kissi, Southern
  tlh = 'tlh', // Klingon; tlhIngan-Hol
  kom = 'kom', // Komi
  kon = 'kon', // Kongo
  kok = 'kok', // Konkani
  kor = 'kor', // Korean
  kpe = 'kpe', // Kpelle
  kro = 'kro', // Kru languages
  kua = 'kua', // Kuanyama; Kwanyama
  kum = 'kum', // Kumyk
  kur = 'kur', // Kurdish
  kru = 'kru', // Kurukh
  kos = 'kos', // Kusaiean (Caroline Islands)
  kut = 'kut', // Kutenai
  fkv = 'fkv', // Kvensk
  kwk = 'kwk', // Kwakiutl
  lad = 'lad', // Ladino
  lah = 'lah', // Lahnda
  lkt = 'lkt', // Lakota
  lam = 'lam', // Lamba
  day = 'day', // Land Dayak languages
  lao = 'lao', // Lao
  lat = 'lat', // Latin
  lav = 'lav', // Latvian
  qlk = 'qlk', // Lemko
  lez = 'lez', // Lezgian
  lij = 'lij', // Ligurian
  lim = 'lim', // Limbergan; Limburger; Limburgish
  lin = 'lin', // Lingala
  lit = 'lit', // Lithuanian
  jbo = 'jbo', // Lojban
  lmo = 'lmo', // Lombard
  nds = 'nds', // Low German; Low Saxon
  dsb = 'dsb', // Lower Sorbian
  loz = 'loz', // Lozi
  lub = 'lub', // Luba-Katanga
  lua = 'lua', // Luba-Lulua
  lui = 'lui', // Luiseño
  smj = 'smj', // Lule Sami
  lun = 'lun', // Lunda
  luo = 'luo', // Luo (Kenya and Tanzania)
  lus = 'lus', // Lushai
  ltz = 'ltz', // Luxembourgish; Letzeburgesch
  mac = 'mac', // Macedonian
  mad = 'mad', // Madurese
  mag = 'mag', // Magahi
  mai = 'mai', // Maithili
  mak = 'mak', // Makasar
  mlg = 'mlg', // Malagasy
  may = 'may', // Malay
  mal = 'mal', // Malayalam
  poz = 'poz', // Malayo-Polynesian languages
  mlt = 'mlt', // Maltese
  mnc = 'mnc', // Manchu
  mdr = 'mdr', // Mandar
  cmn = 'cmn', // Mandarin
  man = 'man', // Mandingo
  mni = 'mni', // Manipuri
  mno = 'mno', // Manobo languages
  glv = 'glv', // Manx
  mao = 'mao', // Maori
  arn = 'arn', // Mapudungun; Mapuche
  mar = 'mar', // Marathi
  chm = 'chm', // Mari
  mah = 'mah', // Marshallese
  mwr = 'mwr', // Marwari
  mas = 'mas', // Masai
  myn = 'myn', // Mayan languages
  fit = 'fit', // Meänkieli / Tornedalen Finnish
  men = 'men', // Mende
  mic = 'mic', // Mi’kmaq; Micmac
  crg = 'crg', // Michif
  gml = 'gml', // Middle Low German
  min = 'min', // Minangkabau
  mwl = 'mwl', // Mirandese
  moh = 'moh', // Mohawk
  mdf = 'mdf', // Moksha
  mol = 'mol', // Moldavian; Moldovan
  mkh = 'mkh', // Mon-Khmer languages
  lol = 'lol', // Mongo-Nkundu
  mon = 'mon', // Mongolian
  cnr = 'cnr', // Montenegrin
  mos = 'mos', // Mooré; Mossi
  crm = 'crm', // Moose Cree
  mun = 'mun', // Munda languages
  mwf = 'mwf', // Murrinh-Patha
  nqo = 'nqo', // N’Ko
  nah = 'nah', // Nahuatl languages
  nsk = 'nsk', // Naskapi
  nau = 'nau', // Nauruan
  nav = 'nav', // Navajo; Navaho
  nde = 'nde', // Ndebele, North
  nbl = 'nbl', // Ndebele, South
  ndo = 'ndo', // Ndonga
  nap = 'nap', // Neapolitan
  nep = 'nep', // Nepali
  qls = 'qls', // Neutral Latin American Spanish
  new = 'new', // Newari; Nepal Bhasa
  nia = 'nia', // Nias
  nic = 'nic', // Niger-Kordofanian languages
  ssa = 'ssa', // Nilo-Saharan languages
  niu = 'niu', // Niuean
  nog = 'nog', // Nogai
  qnf = 'qnf', // Norman French
  nai = 'nai', // North American Indian languages
  crl = 'crl', // Northern East Cree
  frr = 'frr', // Northern Frisian
  sme = 'sme', // Northern Sami
  nor = 'nor', // Norwegian
  nob = 'nob', // Norwegian Bokmål
  nno = 'nno', // Norwegian Nynorsk
  nub = 'nub', // Nubian languages
  nym = 'nym', // Nyamwezi
  nyn = 'nyn', // Nyankole
  nyo = 'nyo', // Nyoro
  nzi = 'nzi', // Nzima
  oci = 'oci', // Occitan (post-1500)
  arc = 'arc', // Official Aramaic; Imperial Aramaic (700-300 BCE)
  oji = 'oji', // Ojibwa
  odt = 'odt', // Old Dutch / Old Low Franconian (ca. 400–1050)
  non = 'non', // Old Norse
  peo = 'peo', // Old Persian (ca. 600-400 B.C.)
  ori = 'ori', // Oriya
  orm = 'orm', // Oromo
  osa = 'osa', // Osage
  oss = 'oss', // Ossetian; Ossetic
  omq = 'omq', // Oto-Manguean languages
  oto = 'oto', // Otomian languages
  pal = 'pal', // Pahlavi
  pau = 'pau', // Palauan
  pli = 'pli', // Pali
  pam = 'pam', // Pampanga; Kapampangan
  pag = 'pag', // Pangasinan
  pan = 'pan', // Panjabi
  pap = 'pap', // Papiamento
  paa = 'paa', // Papuan languages
  nso = 'nso', // Pedi; Sepedi; Northern Sotho
  per = 'per', // Persian
  phi = 'phi', // Philippine languages
  phn = 'phn', // Phoenician
  pcd = 'pcd', // Picard
  qsp = 'qsp', // Picture Communication Symbols (PCS)
  pms = 'pms', // Piedmontese
  crk = 'crk', // Plains Cree
  pol = 'pol', // Polish
  pon = 'pon', // Ponapeian
  por = 'por', // Portuguese
  pra = 'pra', // Prakrit languages
  pro = 'pro', // Provençal, Old (to 1500); Occitan, Old (to 1500)
  pus = 'pus', // Pushto; Pashto
  que = 'que', // Quechua
  raj = 'raj', // Rajasthani
  rap = 'rap', // Rapanui
  rar = 'rar', // Rarotongan; Cook Islands Maori
  rcf = 'rcf', // Réunion Creole French
  rgn = 'rgn', // Romagnol
  roa = 'roa', // Romance languages
  rum = 'rum', // Romanian
  roh = 'roh', // Romansh
  rom = 'rom', // Romany
  run = 'run', // Rundi
  rus = 'rus', // Russian
  sal = 'sal', // Salishan languages
  sam = 'sam', // Samaritan Aramaic
  smi = 'smi', // Sami languages
  smo = 'smo', // Samoan
  sad = 'sad', // Sandawe
  sag = 'sag', // Sango
  san = 'san', // Sanskrit
  sat = 'sat', // Santali
  srm = 'srm', // Saramaccan
  srd = 'srd', // Sardinian
  sas = 'sas', // Sasak
  sdc = 'sdc', // Sassarese
  sco = 'sco', // Scots
  gla = 'gla', // Scottish Gaelic
  sel = 'sel', // Selkup
  sem = 'sem', // Semitic languages
  scc = 'scc', // Serbian
  srp = 'srp', // Serbian
  srr = 'srr', // Serer
  ojs = 'ojs', // Severn Ojibwa
  shn = 'shn', // Shan
  sna = 'sna', // Shona
  shs = 'shs', // Shuswap
  iii = 'iii', // Sichuan Yi; Nuosu
  scn = 'scn', // Sicilian
  sid = 'sid', // Sidamo
  sgn = 'sgn', // Sign languages
  bla = 'bla', // Siksika
  szl = 'szl', // Silesian
  snd = 'snd', // Sindhi
  sin = 'sin', // Sinhala; Sinhalese
  zhx = 'zhx', // Sinitic languages
  sit = 'sit', // Sino-Tibetan languages
  sio = 'sio', // Siouan languages
  sms = 'sms', // Skolt Sami
  den = 'den', // Slave (Athapascan)
  sla = 'sla', // Slavic languages
  slo = 'slo', // Slovak
  slv = 'slv', // Slovenian
  sog = 'sog', // Sogdian
  som = 'som', // Somali
  son = 'son', // Songhai languages
  snk = 'snk', // Soninke
  wen = 'wen', // Sorbian languages
  sot = 'sot', // Sotho; Sesotho
  sai = 'sai', // South American Indian languages
  alt = 'alt', // Southern Altai
  crj = 'crj', // Southern East Cree
  sma = 'sma', // Southern Sami
  spa = 'spa', // Spanish
  srn = 'srn', // Sranan Tongo
  zgh = 'zgh', // Standard Moroccan Tamazight
  sto = 'sto', // Stoney
  suk = 'suk', // Sukuma
  sux = 'sux', // Sumerian
  sun = 'sun', // Sundanese
  sus = 'sus', // Susu
  swa = 'swa', // Swahili
  csw = 'csw', // Swampy Cree
  ssw = 'ssw', // Swazi; Swati
  swe = 'swe', // Swedish
  gsw = 'gsw', // Swiss German; Alemannic; Alsatian
  syr = 'syr', // Syriac
  tgl = 'tgl', // Tagalog
  tah = 'tah', // Tahitian
  tai = 'tai', // Tai languages
  tgk = 'tgk', // Tajik; Tajiki Persian
  tmh = 'tmh', // Tamashek
  tam = 'tam', // Tamil
  shi = 'shi', // Tashelhit; Shilha
  tat = 'tat', // Tatar
  tel = 'tel', // Telugu
  tem = 'tem', // Temne; Time
  ter = 'ter', // Terena
  tet = 'tet', // Tetum
  tha = 'tha', // Thai
  thp = 'thp', // Thompson
  tib = 'tib', // Tibetan
  tig = 'tig', // Tigré
  tir = 'tir', // Tigrinya
  tiv = 'tiv', // Tiv
  tli = 'tli', // Tlingit
  tpi = 'tpi', // Tok Pisin
  tkl = 'tkl', // Tokelauan
  tog = 'tog', // Tonga (Nyasa)
  ton = 'ton', // Tongan
  rmg = 'rmg', // Traveler Norwegian
  tsd = 'tsd', // Tsakonian
  tsi = 'tsi', // Tsimshian
  tso = 'tso', // Tsonga
  tsn = 'tsn', // Tswana
  tum = 'tum', // Tumbuka
  tup = 'tup', // Tupi languages
  tur = 'tur', // Turkish
  ota = 'ota', // Turkish, Ottoman
  tuk = 'tuk', // Turkmen
  tvl = 'tvl', // Tuvaluan
  tyv = 'tyv', // Tuvinian
  twi = 'twi', // Twi
  tzo = 'tzo', // Tzotzil
  udm = 'udm', // Udmurt
  uga = 'uga', // Ugaritic
  uig = 'uig', // Uighur; Uyghur
  ukr = 'ukr', // Ukrainian
  umb = 'umb', // Umbundu
  hsb = 'hsb', // Upper Sorbian
  urj = 'urj', // Uralic languages
  urd = 'urd', // Urdu
  uzb = 'uzb', // Uzbek
  vai = 'vai', // Vai
  qav = 'qav', // Valencian
  ven = 'ven', // Venda
  vec = 'vec', // Venetian/Venetan
  vie = 'vie', // Vietnamese
  vol = 'vol', // Volapük
  vot = 'vot', // Votic
  wak = 'wak', // Wakashan languages
  wls = 'wls', // Wallisian
  wln = 'wln', // Walloon
  war = 'war', // Waray
  was = 'was', // Washo
  guc = 'guc', // Wayuu
  wel = 'wel', // Welsh
  fry = 'fry', // Western Frisian
  qsw = 'qsw', // Widgit symbols
  wal = 'wal', // Wolaitta; Wolaytta
  wol = 'wol', // Wolof
  cwd = 'cwd', // Woods Cree
  wym = 'wym', // Wymysorys
  xho = 'xho', // Xhosa
  sah = 'sah', // Yakut
  yao = 'yao', // Yao
  yap = 'yap', // Yapese
  yid = 'yid', // Yiddish
  yor = 'yor', // Yoruba
  ypk = 'ypk', // Yupik languages
  znd = 'znd', // Zande languages
  zap = 'zap', // Zapotec
  zza = 'zza', // Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki
  zen = 'zen', // Zenaga
  zha = 'zha', // Zhuang; Chuang
  zul = 'zul', // Zulu
  zun = 'zun', // Zuni
  mis = 'mis', // Uncoded language
  und = 'und', // Undetermined language
  mul = 'mul', // Multiple languages
  zxx = 'zxx', // No linguistic content
}