
// https://ns.editeur.org/onix/en/139 
export enum OnixRetailSalesOutletIds {
  SYM = 'SYM', // 24Symbols
  ACM = 'ACM', // A C Moore
  AAP = 'AAP', // AandP
  ADL = 'ADL', // Adlibris
  ACB = 'ACB', // Akademibokhandeln
  AKK = 'AKK', // Akateeminen Kirjakauppa
  ALB = 'ALB', // Albertson’s
  ALT = 'ALT', // AlmaTalent
  AMZ = 'AMZ', // Amazon
  ANR = 'ANR', // Angus and Robertson
  ANB = 'ANB', // Anobii
  APA = 'APA', // Apabi
  APC = 'APC', // Apple
  ASD = 'ASD', // Asda
  ASB = 'ASB', // Asia Books
  AUD = 'AUD', // Audible
  AUC = 'AUC', // Audiobooks.com
  ATK = 'ATK', // Audioteka
  ELU = 'ELU', // Axiell ELibU
  BDL = 'BDL', // B Dalton
  BNO = 'BNO', // Barnes and Noble
  BDZ = 'BDZ', // BDBuzz
  BBB = 'BBB', // Bed Bath and Beyond
  BST = 'BST', // Best Buy
  BOD = 'BOD', // Biblio-on-Demand
  MMM = 'MMM', // Bibliotheca
  BIL = 'BIL', // Bilbary
  BLG = 'BLG', // Billigbook
  BJW = 'BJW', // BJ’s Wholesale Club
  BLA = 'BLA', // Blackstone Audio
  BLK = 'BLK', // Blackwell’s
  GOS = 'GOS', // Blinkbox
  BGI = 'BGI', // Bog & idé
  BSK = 'BSK', // Boksnok
  BSY = 'BSY', // Boksy
  BKU = 'BKU', // Bokus
  BLD = 'BLD', // Bolinda
  BCA = 'BCA', // Book Club Associates
  BDO = 'BDO', // Book d’oreille
  BSL = 'BSL', // Book Solutions
  BOO = 'BOO', // Bookbeat
  BBI = 'BBI', // Bookbites
  BSH = 'BSH', // Bookish
  BMA = 'BMA', // Bookmate
  BKP = 'BKP', // Bookpeople
  BRB = 'BRB', // Books Etc
  BKM = 'BKM', // Books-A-Million
  BKS = 'BKS', // Bookshout
  BTP = 'BTP', // Booktopia
  BKY = 'BKY', // Booky.fi
  BRD = 'BRD', // Borders
  BRT = 'BRT', // British Bookshops
  CAI = 'CAI', // Cairn
  CDL = 'CDL', // Casa del Libro
  CDN = 'CDN', // CDON.com
  CEB = 'CEB', // Ceebo
  CFU = 'CFU', // CFU Danmark
  CHP = 'CHP', // Chapter
  CHD = 'CHD', // Christianbook.com
  CYM = 'CYM', // Citymarket
  CMX = 'CMX', // Comixology
  COP = 'COP', // Copia
  CST = 'CST', // Costco
  CRB = 'CRB', // Crate and Barrel
  CVS = 'CVS', // CVS Drug Stores
  CVM = 'CVM', // CVS Mediatheques
  CYB = 'CYB', // Cyberlibris
  DAU = 'DAU', // Daunt Books
  DEM = 'DEM', // De Marque
  DSG = 'DSG', // Dick’s Sporting Goods
  DIL = 'DIL', // Dilicom
  DYM = 'DYM', // Dymocks
  EPA = 'EPA', // E-Pagine
  ERD = 'ERD', // E-Reads
  ELC = 'ELC', // Early Learning Centre
  ESN = 'ESN', // Eason
  EBC = 'EBC', // Ebooks Corp
  ECH = 'ECH', // eChristian
  ECI = 'ECI', // El Corte Inglés
  ELE = 'ELE', // Electre
  ELB = 'ELB', // Publizon
  ELI = 'ELI', // Elib Library
  ELS = 'ELS', // Elisa
  ELK = 'ELK', // Elisa Kirja Kuukausitilaus
  ELL = 'ELL', // Ellibs.com
  EMP = 'EMP', // Empik
  ENH = 'ENH', // English Heritage
  EPC = 'EPC', // Epic!
  ELN = 'ELN', // Ereolen.dk
  EVB = 'EVB', // Everybook
  FAI = 'FAI', // FairyLoot
  FDB = 'FDB', // FeedBooks
  FIN = 'FIN', // Findaway
  FSP = 'FSP', // Fishpond
  FLP = 'FLP', // FlipKart
  FNC = 'FNC', // Fnac
  FOL = 'FOL', // Follett
  FRY = 'FRY', // Fry’s Electronics
  GMS = 'GMS', // Gamestop
  GAR = 'GAR', // Gardners
  GLO = 'GLO', // Glose
  GOO = 'GOO', // Google Books
  HST = 'HST', // Hastings Entertainment
  HMV = 'HMV', // HMV
  HMD = 'HMD', // Home Depot
  IMM = 'IMM', // Immatériel.fr
  IND = 'IND', // Indigo-Chapters
  INF = 'INF', // Info.fi
  ILT = 'ILT', // Inläsningstjänst
  IBS = 'IBS', // Internet Bookshop Italia
  IZN = 'IZN', // Izneo
  JAM = 'JAM', // Jamera
  JBH = 'JBH', // JB Hifi
  JSM = 'JSM', // John Smith and Son
  KMT = 'KMT', // K-Mart
  KIP = 'KIP', // KIPA
  KID = 'KID', // Kirja&Idea
  KPV = 'KPV', // Kirjastopalvelu
  KRJ = 'KRJ', // Kirja.fi
  KNB = 'KNB', // KNFB/Blio
  KNO = 'KNO', // Kno Inc
  KBO = 'KBO', // Kobo
  KOO = 'KOO', // Koorong
  KOR = 'KOR', // Kortext
  KRG = 'KRG', // Kroger
  LDL = 'LDL', // Lidl
  LEG = 'LEG', // Legible.com
  LEX = 'LEX', // Lexplore
  LTP = 'LTP', // Lehtipiste
  LMB = 'LMB', // LoadMyBook
  LWE = 'LWE', // Lowe’s
  MAC = 'MAC', // Mackin
  MAG = 'MAG', // Magzter
  MNO = 'MNO', // Maneno
  MKS = 'MKS', // Marks and Spencer
  MAT = 'MAT', // Matras
  MMS = 'MMS', // Media Markt/Saturn
  ADP = 'ADP', // Messageries ADP
  MCR = 'MCR', // Microcenter
  MSF = 'MSF', // Microsoft
  MOF = 'MOF', // Mofibo
  MRR = 'MRR', // Morrisons
  MTC = 'MTC', // Mothercare
  MYB = 'MYB', // MyBoox
  MYI = 'MYI', // MyiLibrary
  NTR = 'NTR', // National Trust
  NEX = 'NEX', // NEXT
  NXT = 'NXT', // Nextory
  NUM = 'NUM', // Numilog
  ODL = 'ODL', // Odilo.us
  OFD = 'OFD', // Office Depot
  OFM = 'OFM', // Office Max
  OLF = 'OLF', // OLF
  OVD = 'OVD', // OverDrive
  OYS = 'OYS', // Oyster
  PST = 'PST', // Past Times
  PTS = 'PTS', // Pet Smart
  PTC = 'PTC', // Petco
  PIC = 'PIC', // Piccoma
  PLY = 'PLY', // Play.com
  POD = 'POD', // Podimo
  POY = 'POY', // Podit Oy
  POK = 'POK', // Pokkaritukku
  PTB = 'PTB', // Pottery Barn
  PLO = 'PLO', // Publio
  RDB = 'RDB', // Readbooks
  RCL = 'RCL', // ReadCloud
  RST = 'RST', // Restoration Hardware
  RET = 'RET', // Rethink
  RTZ = 'RTZ', // Ritz Camera
  RMB = 'RMB', // RM Books
  RBD = 'RBD', // Rosebud
  SGR = 'SGR', // S Group
  SAC = 'SAC', // Sacrum
  SAF = 'SAF', // Safari
  SFW = 'SFW', // Safeway
  SNS = 'SNS', // Sainsbury’s
  SAX = 'SAX', // Saxo
  SCR = 'SCR', // Scribd
  SLF = 'SLF', // Selfridges
  SEQ = 'SEQ', // Sequencity
  SES = 'SES', // Sesamy
  SBT = 'SBT', // Shanghai Book Traders
  SKB = 'SKB', // Skoobe
  SMW = 'SMW', // SmashWords
  SNY = 'SNY', // Sony
  SPO = 'SPO', // Spotify
  STP = 'STP', // Staples
  STH = 'STH', // Storyhouse
  STT = 'STT', // Storytel
  SKK = 'SKK', // Suomalainen Kirjakauppa
  SPL = 'SPL', // Suomalainen Plus
  SUP = 'SUP', // Supla+
  SSK = 'SSK', // Suuri Suomalainen Kirjakerho
  TRG = 'TRG', // Target
  TES = 'TES', // Tesco
  TIK = 'TIK', // TikTok Shop
  TOK = 'TOK', // Tokmanni
  TOL = 'TOL', // Tolino
  TSR = 'TSR', // Toys ’R’ Us
  TSO = 'TSO', // TSO (The Stationery Office)
  TKK = 'TKK', // Turun kansallinen kirjakauppa
  TXR = 'TXR', // Txtr
  UBH = 'UBH', // Ugglan Bokhandel
  VRG = 'VRG', // Virgin Megastores
  TEA = 'TEA', // Vivlio
  WHS = 'WHS', // W H Smith
  WTR = 'WTR', // Waitrose
  WLM = 'WLM', // Wal-Mart
  WST = 'WST', // Waterstone’s
  WHT = 'WHT', // Whitcoul’s
  WLS = 'WLS', // Williams Sonoma
  WLW = 'WLW', // Woolworths
  YOU = 'YOU', // Youboox
  YSC = 'YSC', // Youscribe
  ZVV = 'ZVV', // Zavvi
  PUB = 'PUB', // Publisher’s own direct sales
  ZZZ = 'ZZZ', // Other
}