
// https://ns.editeur.org/onix/en/150 
export enum ProductForm {
  _00 = '00', // Undefined
  _AA = 'AA', // Audio
  _AB = 'AB', // Audio cassette
  _AC = 'AC', // CD-Audio
  _AD = 'AD', // DAT
  _AE = 'AE', // Audio disc
  _AF = 'AF', // Audio tape
  _AG = 'AG', // MiniDisc
  _AH = 'AH', // CD-Extra
  _AI = 'AI', // DVD Audio
  _AJ = 'AJ', // Downloadable audio file
  _AK = 'AK', // Pre-recorded digital audio player
  _AL = 'AL', // Pre-recorded SD card
  _AM = 'AM', // LP
  _AN = 'AN', // Downloadable and online audio file
  _AO = 'AO', // Online audio file
  _AZ = 'AZ', // Other audio format
  _BA = 'BA', // Book
  _BB = 'BB', // Hardback
  _BC = 'BC', // Paperback / softback
  _BD = 'BD', // Loose-leaf
  _BE = 'BE', // Spiral bound
  _BF = 'BF', // Pamphlet
  _BG = 'BG', // Leather / fine binding
  _BH = 'BH', // Board book
  _BI = 'BI', // Rag book
  _BJ = 'BJ', // Bath book
  _BK = 'BK', // Novelty book
  _BL = 'BL', // Slide bound
  _BM = 'BM', // Big book
  _BN = 'BN', // Part-work (fascículo)
  _BO = 'BO', // Fold-out book or chart
  _BP = 'BP', // Foam book
  _BZ = 'BZ', // Other book format
  _CA = 'CA', // Sheet map
  _CB = 'CB', // Sheet map, folded
  _CC = 'CC', // Sheet map, flat
  _CD = 'CD', // Sheet map, rolled
  _CE = 'CE', // Globe
  _CZ = 'CZ', // Other cartographic
  _DA = 'DA', // Digital (on physical carrier)
  _DB = 'DB', // CD-ROM
  _DC = 'DC', // CD-I
  _DE = 'DE', // Game cartridge
  _DF = 'DF', // Diskette
  _DI = 'DI', // DVD-ROM
  _DJ = 'DJ', // Secure Digital (SD) Memory Card
  _DK = 'DK', // Compact Flash Memory Card
  _DL = 'DL', // Memory Stick Memory Card
  _DM = 'DM', // USB Flash Drive
  _DN = 'DN', // Double-sided CD/DVD
  _DO = 'DO', // BR-ROM
  _DZ = 'DZ', // Other digital carrier
  _EA = 'EA', // Digital (delivered electronically)
  _EB = 'EB', // Digital download and online
  _EC = 'EC', // Digital online
  _ED = 'ED', // Digital download
  _FA = 'FA', // Film or transparency
  _FC = 'FC', // Slides
  _FD = 'FD', // OHP transparencies
  _FE = 'FE', // Filmstrip
  _FF = 'FF', // Film
  _FZ = 'FZ', // Other film or transparency format
  _LA = 'LA', // Digital product license
  _LB = 'LB', // Digital product license key
  _LC = 'LC', // Digital product license code
  _MA = 'MA', // Microform
  _MB = 'MB', // Microfiche
  _MC = 'MC', // Microfilm
  _MZ = 'MZ', // Other microform
  _PA = 'PA', // Miscellaneous print
  _PB = 'PB', // Address book
  _PC = 'PC', // Calendar
  _PD = 'PD', // Cards
  _PE = 'PE', // Copymasters
  _PF = 'PF', // Diary or journal
  _PG = 'PG', // Frieze
  _PH = 'PH', // Kit
  _PI = 'PI', // Sheet music
  _PJ = 'PJ', // Postcard book or pack
  _PK = 'PK', // Poster
  _PL = 'PL', // Record book
  _PM = 'PM', // Wallet or folder
  _PN = 'PN', // Pictures or photographs
  _PO = 'PO', // Wallchart
  _PP = 'PP', // Stickers
  _PQ = 'PQ', // Plate (lámina)
  _PR = 'PR', // Notebook / blank book
  _PS = 'PS', // Organizer
  _PT = 'PT', // Bookmark
  _PU = 'PU', // Leaflet
  _PV = 'PV', // Book plates
  _PZ = 'PZ', // Other printed item
  _SA = 'SA', // Multiple-component retail product
  _SB = 'SB', // Multiple-component retail product, boxed
  _SC = 'SC', // Multiple-component retail product, slip-cased
  _SD = 'SD', // Multiple-component retail product, shrink-wrapped
  _SE = 'SE', // Multiple-component retail product, loose
  _SF = 'SF', // Multiple-component retail product, part(s) enclosed
  _SG = 'SG', // Multiple-component retail product, entirely digital
  _VA = 'VA', // Video
  _VF = 'VF', // Videodisc
  _VI = 'VI', // DVD video
  _VJ = 'VJ', // VHS video
  _VK = 'VK', // Betamax video
  _VL = 'VL', // VCD
  _VM = 'VM', // SVCD
  _VN = 'VN', // HD DVD
  _VO = 'VO', // Blu-ray
  _VP = 'VP', // UMD Video
  _VQ = 'VQ', // CBHD
  _VZ = 'VZ', // Other video format
  _XA = 'XA', // Trade-only material
  _XB = 'XB', // Dumpbin – empty
  _XC = 'XC', // Dumpbin – filled
  _XD = 'XD', // Counterpack – empty
  _XE = 'XE', // Counterpack – filled
  _XF = 'XF', // Poster, promotional
  _XG = 'XG', // Shelf strip
  _XH = 'XH', // Window piece
  _XI = 'XI', // Streamer
  _XJ = 'XJ', // Spinner – empty
  _XK = 'XK', // Large book display
  _XL = 'XL', // Shrink-wrapped pack
  _XM = 'XM', // Boxed pack
  _XN = 'XN', // Pack (outer packaging unspecified)
  _XO = 'XO', // Spinner – filled
  _XY = 'XY', // Other point of sale – including retail product
  _XZ = 'XZ', // Other point of sale
  _ZA = 'ZA', // General merchandise
  _ZB = 'ZB', // Doll or figure
  _ZC = 'ZC', // Soft toy
  _ZD = 'ZD', // Toy
  _ZE = 'ZE', // Game
  _ZF = 'ZF', // T-shirt
  _ZG = 'ZG', // E-book reader
  _ZH = 'ZH', // Tablet computer
  _ZI = 'ZI', // Audiobook player
  _ZJ = 'ZJ', // Jigsaw
  _ZK = 'ZK', // Mug
  _ZL = 'ZL', // Tote bag
  _ZM = 'ZM', // Tableware
  _ZN = 'ZN', // Umbrella
  _ZO = 'ZO', // Paints, crayons, pencils
  _ZP = 'ZP', // Handicraft kit
  _ZX = 'ZX', // Other toy/game accessories
  _ZY = 'ZY', // Other apparel
  _ZZ = 'ZZ', // Other merchandise
}