
// https://ns.editeur.org/onix/en/49 
export enum RegionBasedOnIso31662 {
  AU_CT = 'AU_CT', // Australian Capital Territory
  AU_NS = 'AU_NS', // New South Wales
  AU_NT = 'AU_NT', // Northern Territory
  AU_QL = 'AU_QL', // Queensland
  AU_SA = 'AU_SA', // South Australia
  AU_TS = 'AU_TS', // Tasmania
  AU_VI = 'AU_VI', // Victoria
  AU_WA = 'AU_WA', // Western Australia
  BE_BRU = 'BE_BRU', // Brussels-Capital Region
  BE_VLG = 'BE_VLG', // Flemish Region
  BE_WAL = 'BE_WAL', // Walloon Region
  CA_AB = 'CA_AB', // Alberta
  CA_BC = 'CA_BC', // British Columbia
  CA_MB = 'CA_MB', // Manitoba
  CA_NB = 'CA_NB', // New Brunswick
  CA_NL = 'CA_NL', // Newfoundland and Labrador
  CA_NS = 'CA_NS', // Nova Scotia
  CA_NT = 'CA_NT', // Northwest Territories
  CA_NU = 'CA_NU', // Nunavut
  CA_ON = 'CA_ON', // Ontario
  CA_PE = 'CA_PE', // Prince Edward Island
  CA_QC = 'CA_QC', // Quebec
  CA_SK = 'CA_SK', // Saskatchewan
  CA_YT = 'CA_YT', // Yukon Territory
  CN_BJ = 'CN_BJ', // Beijing Municipality
  CN_TJ = 'CN_TJ', // Tianjin Municipality
  CN_HE = 'CN_HE', // Hebei Province
  CN_SX = 'CN_SX', // Shanxi Province
  CN_NM = 'CN_NM', // Nei Mongol Autonomous Region
  CN_LN = 'CN_LN', // Liaoning Province
  CN_JL = 'CN_JL', // Jilin Province
  CN_HL = 'CN_HL', // Heilongjiang Province
  CN_SH = 'CN_SH', // Shanghai Municipality
  CN_JS = 'CN_JS', // Jiangsu Province
  CN_ZJ = 'CN_ZJ', // Zhejiang Province
  CN_AH = 'CN_AH', // Anhui Province
  CN_FJ = 'CN_FJ', // Fujian Province
  CN_JX = 'CN_JX', // Jiangxi Province
  CN_SD = 'CN_SD', // Shandong Province
  CN_HA = 'CN_HA', // Henan Province
  CN_HB = 'CN_HB', // Hubei Province
  CN_HN = 'CN_HN', // Hunan Province
  CN_GD = 'CN_GD', // Guangdong Province
  CN_GX = 'CN_GX', // Guangxi Zhuangzu Autonomous Region
  CN_HI = 'CN_HI', // Hainan Province
  CN_CQ = 'CN_CQ', // Chongqing Municipality
  CN_SC = 'CN_SC', // Sichuan Province
  CN_GZ = 'CN_GZ', // Guizhou Province
  CN_YN = 'CN_YN', // Yunnan Province
  CN_XZ = 'CN_XZ', // Tibet Autonomous Region
  CN_SN = 'CN_SN', // Shaanxi Province
  CN_GS = 'CN_GS', // Gansu Province
  CN_QH = 'CN_QH', // Qinghai Province
  CN_NX = 'CN_NX', // Ningxia Huizu Autonomous Region
  CN_XJ = 'CN_XJ', // Xinjiang Uygur Autonomous Region
  CN_TW = 'CN_TW', // Taiwan Province
  CN_HK = 'CN_HK', // Hong Kong Special Administrative Region
  CN_MO = 'CN_MO', // Macau Special Administrative Region
  CN_11 = 'CN_11', // Beijing Municipality
  CN_12 = 'CN_12', // Tianjin Municipality
  CN_13 = 'CN_13', // Hebei Province
  CN_14 = 'CN_14', // Shanxi Province
  CN_15 = 'CN_15', // Inner Mongolia Autonomous Region
  CN_21 = 'CN_21', // Liaoning Province
  CN_22 = 'CN_22', // Jilin Province
  CN_23 = 'CN_23', // Heilongjiang Province
  CN_31 = 'CN_31', // Shanghai Municipality
  CN_32 = 'CN_32', // Jiangsu Province
  CN_33 = 'CN_33', // Zhejiang Province
  CN_34 = 'CN_34', // Anhui Province
  CN_35 = 'CN_35', // Fujian Province
  CN_36 = 'CN_36', // Jiangxi Province
  CN_37 = 'CN_37', // Shandong Province
  CN_41 = 'CN_41', // Henan Province
  CN_42 = 'CN_42', // Hubei Province
  CN_43 = 'CN_43', // Hunan Province
  CN_44 = 'CN_44', // Guangdong Province
  CN_45 = 'CN_45', // Guangxi Zhuang Autonomous Region
  CN_46 = 'CN_46', // Hainan Province
  CN_50 = 'CN_50', // Chongqing Municipality
  CN_51 = 'CN_51', // Sichuan Province
  CN_52 = 'CN_52', // Guizhou Province
  CN_53 = 'CN_53', // Yunnan Province
  CN_54 = 'CN_54', // Tibet Autonomous Region
  CN_61 = 'CN_61', // Shaanxi Province
  CN_62 = 'CN_62', // Gansu Province
  CN_63 = 'CN_63', // Qinghai Province
  CN_64 = 'CN_64', // Ningxia Hui Autonomous Region
  CN_65 = 'CN_65', // Xinjiang Uyghur Autonomous Region
  CN_71 = 'CN_71', // Taiwan Province
  CN_91 = 'CN_91', // Hong Kong Special Administrative Region
  CN_92 = 'CN_92', // Macau Special Administrative Region
  ES_CN = 'ES_CN', // Canary Islands
  FR_H = 'FR_H', // Corsica
  GB_AIR = 'GB_AIR', // UK airside
  GB_APS = 'GB_APS', // UK airports
  GB_CHA = 'GB_CHA', // Channel Islands
  GB_ENG = 'GB_ENG', // England
  GB_EWS = 'GB_EWS', // England, Wales, Scotland
  GB_IOM = 'GB_IOM', // Isle of Man
  GB_NIR = 'GB_NIR', // Northern Ireland
  GB_SCT = 'GB_SCT', // Scotland
  GB_WLS = 'GB_WLS', // Wales
  IE_AIR = 'IE_AIR', // Ireland airside
  IT_AG = 'IT_AG', // Agrigento
  IT_AL = 'IT_AL', // Alessandria
  IT_AN = 'IT_AN', // Ancona
  IT_AO = 'IT_AO', // Aosta
  IT_AR = 'IT_AR', // Arezzo
  IT_AP = 'IT_AP', // Ascoli Piceno
  IT_AT = 'IT_AT', // Asti
  IT_AV = 'IT_AV', // Avellino
  IT_BA = 'IT_BA', // Bari
  IT_BT = 'IT_BT', // Barletta-Andria-Trani
  IT_BL = 'IT_BL', // Belluno
  IT_BN = 'IT_BN', // Benevento
  IT_BG = 'IT_BG', // Bergamo
  IT_BI = 'IT_BI', // Biella
  IT_BO = 'IT_BO', // Bologna
  IT_BZ = 'IT_BZ', // Bolzano
  IT_BS = 'IT_BS', // Brescia
  IT_BR = 'IT_BR', // Brindisi
  IT_CA = 'IT_CA', // Cagliari
  IT_CL = 'IT_CL', // Caltanissetta
  IT_CB = 'IT_CB', // Campobasso
  IT_CI = 'IT_CI', // Carbonia-Iglesias
  IT_CE = 'IT_CE', // Caserta
  IT_CT = 'IT_CT', // Catania
  IT_CZ = 'IT_CZ', // Catanzaro
  IT_CH = 'IT_CH', // Chieti
  IT_CO = 'IT_CO', // Como
  IT_CS = 'IT_CS', // Cosenza
  IT_CR = 'IT_CR', // Cremona
  IT_KR = 'IT_KR', // Crotone
  IT_CN = 'IT_CN', // Cuneo
  IT_EN = 'IT_EN', // Enna
  IT_FM = 'IT_FM', // Fermo
  IT_FE = 'IT_FE', // Ferrara
  IT_FI = 'IT_FI', // Firenze
  IT_FG = 'IT_FG', // Foggia
  IT_FC = 'IT_FC', // Forlì-Cesena
  IT_FR = 'IT_FR', // Frosinone
  IT_GE = 'IT_GE', // Genova
  IT_GO = 'IT_GO', // Gorizia
  IT_GR = 'IT_GR', // Grosseto
  IT_IM = 'IT_IM', // Imperia
  IT_IS = 'IT_IS', // Isernia
  IT_SP = 'IT_SP', // La Spezia
  IT_AQ = 'IT_AQ', // L’Aquila
  IT_LT = 'IT_LT', // Latina
  IT_LE = 'IT_LE', // Lecce
  IT_LC = 'IT_LC', // Lecco
  IT_LI = 'IT_LI', // Livorno
  IT_LO = 'IT_LO', // Lodi
  IT_LU = 'IT_LU', // Lucca
  IT_MC = 'IT_MC', // Macerata
  IT_MN = 'IT_MN', // Mantova
  IT_MS = 'IT_MS', // Massa-Carrara
  IT_MT = 'IT_MT', // Matera
  IT_VS = 'IT_VS', // Medio Campidano
  IT_ME = 'IT_ME', // Messina
  IT_MI = 'IT_MI', // Milano
  IT_MO = 'IT_MO', // Modena
  IT_MB = 'IT_MB', // Monza e Brianza
  IT_NA = 'IT_NA', // Napoli
  IT_NO = 'IT_NO', // Novara
  IT_NU = 'IT_NU', // Nuoro
  IT_OG = 'IT_OG', // Ogliastra
  IT_OT = 'IT_OT', // Olbia-Tempio
  IT_OR = 'IT_OR', // Oristano
  IT_PD = 'IT_PD', // Padova
  IT_PA = 'IT_PA', // Palermo
  IT_PR = 'IT_PR', // Parma
  IT_PV = 'IT_PV', // Pavia
  IT_PG = 'IT_PG', // Perugia
  IT_PU = 'IT_PU', // Pesaro e Urbino
  IT_PE = 'IT_PE', // Pescara
  IT_PC = 'IT_PC', // Piacenza
  IT_PI = 'IT_PI', // Pisa
  IT_PT = 'IT_PT', // Pistoia
  IT_PN = 'IT_PN', // Pordenone
  IT_PZ = 'IT_PZ', // Potenza
  IT_PO = 'IT_PO', // Prato
  IT_RG = 'IT_RG', // Ragusa
  IT_RA = 'IT_RA', // Ravenna
  IT_RC = 'IT_RC', // Reggio Calabria
  IT_RE = 'IT_RE', // Reggio Emilia
  IT_RI = 'IT_RI', // Rieti
  IT_RN = 'IT_RN', // Rimini
  IT_RM = 'IT_RM', // Roma
  IT_RO = 'IT_RO', // Rovigo
  IT_SA = 'IT_SA', // Salerno
  IT_SS = 'IT_SS', // Sassari
  IT_SV = 'IT_SV', // Savona
  IT_SI = 'IT_SI', // Siena
  IT_SR = 'IT_SR', // Siracusa
  IT_SO = 'IT_SO', // Sondrio
  IT_TA = 'IT_TA', // Taranto
  IT_TE = 'IT_TE', // Teramo
  IT_TR = 'IT_TR', // Terni
  IT_TO = 'IT_TO', // Torino
  IT_TP = 'IT_TP', // Trapani
  IT_TN = 'IT_TN', // Trento
  IT_TV = 'IT_TV', // Treviso
  IT_TS = 'IT_TS', // Trieste
  IT_UD = 'IT_UD', // Udine
  IT_VA = 'IT_VA', // Varese
  IT_VE = 'IT_VE', // Venezia
  IT_VB = 'IT_VB', // Verbano-Cusio-Ossola
  IT_VC = 'IT_VC', // Vercelli
  IT_VR = 'IT_VR', // Verona
  IT_VV = 'IT_VV', // Vibo Valentia
  IT_VI = 'IT_VI', // Vicenza
  IT_VT = 'IT_VT', // Viterbo
  RS_KM = 'RS_KM', // Kosovo-Metohija
  RS_VO = 'RS_VO', // Vojvodina
  RU_AD = 'RU_AD', // Republic of Adygeya
  RU_AL = 'RU_AL', // Republic of Altay
  RU_BA = 'RU_BA', // Republic of Bashkortostan
  RU_BU = 'RU_BU', // Republic of Buryatiya
  RU_CE = 'RU_CE', // Chechenskaya Republic
  RU_CU = 'RU_CU', // Chuvashskaya Republic
  RU_DA = 'RU_DA', // Republic of Dagestan
  RU_IN = 'RU_IN', // Republic of Ingushetiya
  RU_KB = 'RU_KB', // Kabardino-Balkarskaya Republic
  RU_KL = 'RU_KL', // Republic of Kalmykiya
  RU_KC = 'RU_KC', // Karachayevo-Cherkesskaya Republic
  RU_KR = 'RU_KR', // Republic of Kareliya
  RU_KK = 'RU_KK', // Republic of Khakasiya
  RU_KO = 'RU_KO', // Republic of Komi
  RU_ME = 'RU_ME', // Republic of Mariy El
  RU_MO = 'RU_MO', // Republic of Mordoviya
  RU_SA = 'RU_SA', // Republic of Sakha (Yakutiya)
  RU_SE = 'RU_SE', // Republic of Severnaya Osetiya-Alaniya
  RU_TA = 'RU_TA', // Republic of Tatarstan
  RU_TY = 'RU_TY', // Republic of Tyva (Tuva)
  RU_UD = 'RU_UD', // Udmurtskaya Republic
  RU_ALT = 'RU_ALT', // Altayskiy Administrative Territory
  RU_KAM = 'RU_KAM', // Kamchatskiy Administrative Territory
  RU_KHA = 'RU_KHA', // Khabarovskiy Administrative Territory
  RU_KDA = 'RU_KDA', // Krasnodarskiy Administrative Territory
  RU_KYA = 'RU_KYA', // Krasnoyarskiy Administrative Territory
  RU_PER = 'RU_PER', // Permskiy Administrative Territory
  RU_PRI = 'RU_PRI', // Primorskiy Administrative Territory
  RU_STA = 'RU_STA', // Stavropol’skiy Administrative Territory
  RU_ZAB = 'RU_ZAB', // Zabaykal’skiy Administrative Territory
  RU_AMU = 'RU_AMU', // Amurskaya Administrative Region
  RU_ARK = 'RU_ARK', // Arkhangel’skaya Administrative Region
  RU_AST = 'RU_AST', // Astrakhanskaya Administrative Region
  RU_BEL = 'RU_BEL', // Belgorodskaya Administrative Region
  RU_BRY = 'RU_BRY', // Bryanskaya Administrative Region
  RU_CHE = 'RU_CHE', // Chelyabinskaya Administrative Region
  RU_IRK = 'RU_IRK', // Irkutskaya Administrative Region
  RU_IVA = 'RU_IVA', // Ivanovskaya Administrative Region
  RU_KGD = 'RU_KGD', // Kaliningradskaya Administrative Region
  RU_KLU = 'RU_KLU', // Kaluzhskaya Administrative Region
  RU_KEM = 'RU_KEM', // Kemerovskaya Administrative Region
  RU_KIR = 'RU_KIR', // Kirovskaya Administrative Region
  RU_KOS = 'RU_KOS', // Kostromskaya Administrative Region
  RU_KGN = 'RU_KGN', // Kurganskaya Administrative Region
  RU_KRS = 'RU_KRS', // Kurskaya Administrative Region
  RU_LEN = 'RU_LEN', // Leningradskaya Administrative Region
  RU_LIP = 'RU_LIP', // Lipetskaya Administrative Region
  RU_MAG = 'RU_MAG', // Magadanskaya Administrative Region
  RU_MOS = 'RU_MOS', // Moskovskaya Administrative Region
  RU_MUR = 'RU_MUR', // Murmanskaya Administrative Region
  RU_NIZ = 'RU_NIZ', // Nizhegorodskaya Administrative Region
  RU_NGR = 'RU_NGR', // Novgorodskaya Administrative Region
  RU_NVS = 'RU_NVS', // Novosibirskaya Administrative Region
  RU_OMS = 'RU_OMS', // Omskaya Administrative Region
  RU_ORE = 'RU_ORE', // Orenburgskaya Administrative Region
  RU_ORL = 'RU_ORL', // Orlovskaya Administrative Region
  RU_PNZ = 'RU_PNZ', // Penzenskaya Administrative Region
  RU_PSK = 'RU_PSK', // Pskovskaya Administrative Region
  RU_ROS = 'RU_ROS', // Rostovskaya Administrative Region
  RU_RYA = 'RU_RYA', // Ryazanskaya Administrative Region
  RU_SAK = 'RU_SAK', // Sakhalinskaya Administrative Region
  RU_SAM = 'RU_SAM', // Samarskaya Administrative Region
  RU_SAR = 'RU_SAR', // Saratovskaya Administrative Region
  RU_SMO = 'RU_SMO', // Smolenskaya Administrative Region
  RU_SVE = 'RU_SVE', // Sverdlovskaya Administrative Region
  RU_TAM = 'RU_TAM', // Tambovskaya Administrative Region
  RU_TOM = 'RU_TOM', // Tomskaya Administrative Region
  RU_TUL = 'RU_TUL', // Tul’skaya Administrative Region
  RU_TVE = 'RU_TVE', // Tverskaya Administrative Region
  RU_TYU = 'RU_TYU', // Tyumenskaya Administrative Region
  RU_ULY = 'RU_ULY', // Ul’yanovskaya Administrative Region
  RU_VLA = 'RU_VLA', // Vladimirskaya Administrative Region
  RU_VGG = 'RU_VGG', // Volgogradskaya Administrative Region
  RU_VLG = 'RU_VLG', // Vologodskaya Administrative Region
  RU_VOR = 'RU_VOR', // Voronezhskaya Administrative Region
  RU_YAR = 'RU_YAR', // Yaroslavskaya Administrative Region
  RU_MOW = 'RU_MOW', // Moskva City
  RU_SPE = 'RU_SPE', // Sankt-Peterburg City
  RU_YEV = 'RU_YEV', // Yevreyskaya Autonomous Administrative Region
  RU_CHU = 'RU_CHU', // Chukotskiy Autonomous District
  RU_KHM = 'RU_KHM', // Khanty-Mansiyskiy Autonomous District
  RU_NEN = 'RU_NEN', // Nenetskiy Autonomous District
  RU_YAN = 'RU_YAN', // Yamalo-Nenetskiy Autonomous District
  US_AK = 'US_AK', // Alaska
  US_AL = 'US_AL', // Alabama
  US_AR = 'US_AR', // Arkansas
  US_AZ = 'US_AZ', // Arizona
  US_CA = 'US_CA', // California
  US_CO = 'US_CO', // Colorado
  US_CT = 'US_CT', // Connecticut
  US_DC = 'US_DC', // District of Columbia
  US_DE = 'US_DE', // Delaware
  US_FL = 'US_FL', // Florida
  US_GA = 'US_GA', // Georgia
  US_HI = 'US_HI', // Hawaii
  US_IA = 'US_IA', // Iowa
  US_ID = 'US_ID', // Idaho
  US_IL = 'US_IL', // Illinois
  US_IN = 'US_IN', // Indiana
  US_KS = 'US_KS', // Kansas
  US_KY = 'US_KY', // Kentucky
  US_LA = 'US_LA', // Louisiana
  US_MA = 'US_MA', // Massachusetts
  US_MD = 'US_MD', // Maryland
  US_ME = 'US_ME', // Maine
  US_MI = 'US_MI', // Michigan
  US_MN = 'US_MN', // Minnesota
  US_MO = 'US_MO', // Missouri
  US_MS = 'US_MS', // Mississippi
  US_MT = 'US_MT', // Montana
  US_NC = 'US_NC', // North Carolina
  US_ND = 'US_ND', // North Dakota
  US_NE = 'US_NE', // Nebraska
  US_NH = 'US_NH', // New Hampshire
  US_NJ = 'US_NJ', // New Jersey
  US_NM = 'US_NM', // New Mexico
  US_NV = 'US_NV', // Nevada
  US_NY = 'US_NY', // New York
  US_OH = 'US_OH', // Ohio
  US_OK = 'US_OK', // Oklahoma
  US_OR = 'US_OR', // Oregon
  US_PA = 'US_PA', // Pennsylvania
  US_RI = 'US_RI', // Rhode Island
  US_SC = 'US_SC', // South Carolina
  US_SD = 'US_SD', // South Dakota
  US_TN = 'US_TN', // Tennessee
  US_TX = 'US_TX', // Texas
  US_UT = 'US_UT', // Utah
  US_VA = 'US_VA', // Virginia
  US_VT = 'US_VT', // Vermont
  US_WA = 'US_WA', // Washington
  US_WI = 'US_WI', // Wisconsin
  US_WV = 'US_WV', // West Virginia
  US_WY = 'US_WY', // Wyoming
  ECZ = 'ECZ', // Eurozone
  WORLD = 'WORLD', // World
}
