
// https://ns.editeur.org/onix/en/27 
export enum SubjectSchemeIdentifier {
  _01 = '01', // Dewey
  _02 = '02', // Abridged Dewey
  _03 = '03', // LC classification
  _04 = '04', // LC subject heading
  _05 = '05', // NLM classification
  _06 = '06', // MeSH heading
  _07 = '07', // NAL subject heading
  _08 = '08', // AAT
  _09 = '09', // UDC
  _10 = '10', // BISAC Subject Heading
  _11 = '11', // BISAC Regional theme
  _12 = '12', // BIC subject category
  _13 = '13', // BIC geographical qualifier
  _14 = '14', // BIC language qualifier (language as subject)
  _15 = '15', // BIC time period qualifier
  _16 = '16', // BIC educational purpose qualifier
  _17 = '17', // BIC reading level and special interest qualifier
  _18 = '18', // DDC-Sachgruppen der Deutschen Nationalbibliografie
  _19 = '19', // LC fiction genre heading
  _20 = '20', // Keywords
  _21 = '21', // BIC children’s book marketing category
  _22 = '22', // BISAC Merchandising Theme
  _23 = '23', // Publisher’s own category code
  _24 = '24', // Proprietary subject scheme
  _25 = '25', // Tabla de materias ISBN
  _26 = '26', // Warengruppen-Systematik des deutschen Buchhandels
  _27 = '27', // SWD
  _28 = '28', // Thèmes Electre
  _29 = '29', // CLIL Classification thématique
  _30 = '30', // DNB-Sachgruppen
  _31 = '31', // NUGI
  _32 = '32', // NUR
  _33 = '33', // ECPA Christian Book Category
  _34 = '34', // SISO
  _35 = '35', // Korean Decimal Classification (KDC)
  _36 = '36', // DDC Deutsch 22
  _37 = '37', // Bokgrupper
  _38 = '38', // Varegrupper
  _39 = '39', // Læreplaner-KL06
  _40 = '40', // Nippon Decimal Classification
  _41 = '41', // BSQ
  _42 = '42', // ANELE Materias
  _43 = '43', // Utdanningsprogram
  _44 = '44', // Programområde
  _45 = '45', // Undervisningsmateriell
  _46 = '46', // Norsk DDK
  _47 = '47', // Varugrupper
  _48 = '48', // SAB
  _49 = '49', // Läromedelstyp
  _50 = '50', // Förhandsbeskrivning
  _51 = '51', // Spanish ISBN UDC subset
  _52 = '52', // ECI subject categories
  _53 = '53', // Soggetto CCE
  _54 = '54', // Qualificatore geografico CCE
  _55 = '55', // Qualificatore di lingua CCE
  _56 = '56', // Qualificatore di periodo storico CCE
  _57 = '57', // Qualificatore di livello scolastico CCE
  _58 = '58', // Qualificatore di età di lettura CCE
  _59 = '59', // VdS Bildungsmedien Fächer
  _60 = '60', // Fagkoder
  _61 = '61', // JEL classification
  _62 = '62', // CSH
  _63 = '63', // RVM
  _64 = '64', // YSA
  _65 = '65', // Allärs
  _66 = '66', // YKL
  _67 = '67', // MUSA
  _68 = '68', // CILLA
  _69 = '69', // Kaunokki
  _70 = '70', // Bella
  _71 = '71', // YSO
  _72 = '72', // PTO
  _73 = '73', // Suomalainen kirja-alan luokitus
  _74 = '74', // Sears
  _75 = '75', // BIC E4L
  _76 = '76', // CSR
  _77 = '77', // Suomalainen oppiaineluokitus
  _78 = '78', // Japanese book trade C-Code
  _79 = '79', // Japanese book trade Genre Code
  _80 = '80', // Fiktiivisen aineiston lisäluokitus
  _81 = '81', // Arabic Subject heading scheme
  _82 = '82', // Arabized BIC subject category
  _83 = '83', // Arabized LC subject headings
  _84 = '84', // Bibliotheca Alexandrina Subject Headings
  _85 = '85', // Postal code
  _86 = '86', // GeoNames ID
  _87 = '87', // NewBooks Subject Classification
  _88 = '88', // Chinese Library Classification
  _89 = '89', // NTCPDSAC Classification
  _90 = '90', // Season and Event Indicator
  _91 = '91', // GND
  _92 = '92', // BIC UKSLC
  _93 = '93', // Thema subject category
  _94 = '94', // Thema place qualifier
  _95 = '95', // Thema language qualifier
  _96 = '96', // Thema time period qualifier
  _97 = '97', // Thema educational purpose qualifier
  _98 = '98', // Thema interest age / special interest qualifier
  _99 = '99', // Thema style qualifier
  _A2 = 'A2', // Ämnesord
  _A3 = 'A3', // Statystyka Książek Papierowych, Mówionych I Elektronicznych
  _A4 = 'A4', // CCSS
  _A5 = 'A5', // Rameau
  _A6 = 'A6', // Nomenclature discipline scolaire
  _A7 = 'A7', // ISIC
  _A8 = 'A8', // LC Children’s Subject Headings
  _A9 = 'A9', // Ny Läromedel
  _B0 = 'B0', // EuroVoc
  _B1 = 'B1', // BISG Educational Taxonomy
  _B2 = 'B2', // Keywords (not for display)
  _B3 = 'B3', // Nomenclature Diplôme
  _B4 = 'B4', // Key character names
  _B5 = 'B5', // Key place names
  _B6 = 'B6', // FAST
  _B7 = 'B7', // NGSS
  _B8 = 'B8', // MVB-Lesemotive
  _B9 = 'B9', // LOPS21 Subject module
  _C0 = 'C0', // Læreplaner-LK20
  _C1 = 'C1', // Kompetansemål-LK20
  _C2 = 'C2', // Kompetansemålsett-LK20
  _C3 = 'C3', // Tverrfaglige temaer-LK20
  _C4 = 'C4', // CLIL – Type d’article scolaire
  _C5 = 'C5', // GAR – Type pédagogique
  _C6 = 'C6', // ISCED-F
  _C7 = 'C7', // Klassifikationen von Spielen, Puzzles und Spielwaren
  _C8 = 'C8', // NBVok NTSF
  _C9 = 'C9', // JPRO Genre
  _D0 = 'D0', // KAUNO
  _D1 = 'D1', // SLM
  _D2 = 'D2', // YSO-places
}