
// https://ns.editeur.org/onix/en/121 
export enum TextScriptBasedOnIso15924 {
  Adlm = 'Adlm', // Adlam
  Afak = 'Afak', // Afaka
  Aghb = 'Aghb', // Caucasian Albanian
  Ahom = 'Ahom', // Ahom, Tai Ahom
  Arab = 'Arab', // Arabic
  Aran = 'Aran', // Arabic (Nastaliq variant)
  Armi = 'Armi', // Imperial Aramaic
  Armn = 'Armn', // Armenian
  Avst = 'Avst', // Avestan
  Bali = 'Bali', // Balinese
  Bamu = 'Bamu', // Bamun
  Bass = 'Bass', // Bassa Vah
  Batk = 'Batk', // Batak
  Beng = 'Beng', // Bengali (Bangla)
  Bhks = 'Bhks', // Bhaiksuki
  Blis = 'Blis', // Blissymbols
  Bopo = 'Bopo', // Bopomofo
  Brah = 'Brah', // Brahmi
  Brai = 'Brai', // Braille
  Bugi = 'Bugi', // Buginese
  Buhd = 'Buhd', // Buhid
  Cakm = 'Cakm', // Chakma
  Cans = 'Cans', // Unified Canadian Aboriginal Syllabics
  Cari = 'Cari', // Carian
  Cham = 'Cham', // Cham
  Cher = 'Cher', // Cherokee
  Chrs = 'Chrs', // Chorasmian
  Cirt = 'Cirt', // Cirth
  Copt = 'Copt', // Coptic
  Cpmn = 'Cpmn', // Cypro-Minoan
  Cprt = 'Cprt', // Cypriot
  Cyrl = 'Cyrl', // Cyrillic
  Cyrs = 'Cyrs', // Cyrillic (Old Church Slavonic variant)
  Deva = 'Deva', // Devanagari (Nagari)
  Diak = 'Diak', // Dives Akuru
  Dogr = 'Dogr', // Dogra
  Dsrt = 'Dsrt', // Deseret (Mormon)
  Dupl = 'Dupl', // Duployan shorthand, Duployan stenography
  Egyd = 'Egyd', // Egyptian demotic
  Egyh = 'Egyh', // Egyptian hieratic
  Egyp = 'Egyp', // Egyptian hieroglyphs
  Elba = 'Elba', // Elbasan
  Elym = 'Elym', // Elymaic
  Ethi = 'Ethi', // Ethiopic (Ge‘ez)
  Geok = 'Geok', // Khutsuri (Asomtavruli and Khutsuri)
  Geor = 'Geor', // Georgian (Mkhedruli and Mtavruli)
  Glag = 'Glag', // Glagolitic
  Gong = 'Gong', // Gunjala Gondi
  Gonm = 'Gonm', // Masaram Gondi
  Goth = 'Goth', // Gothic
  Gran = 'Gran', // Grantha
  Grek = 'Grek', // Greek
  Gujr = 'Gujr', // Gujarati
  Guru = 'Guru', // Gurmukhi
  Hanb = 'Hanb', // Han with Bopomofo
  Hang = 'Hang', // Hangul (Hangŭl, Hangeul)
  Hani = 'Hani', // Han (Hanzi, Kanji, Hanja)
  Hano = 'Hano', // Hanunoo (Hanunóo)
  Hans = 'Hans', // Han (Simplified variant)
  Hant = 'Hant', // Han (Traditional variant)
  Hatr = 'Hatr', // Hatran
  Hebr = 'Hebr', // Hebrew
  Hira = 'Hira', // Hiragana
  Hluw = 'Hluw', // Anatolian Hieroglyphs (Luwian Hieroglyphs, Hittite Hieroglyphs)
  Hmng = 'Hmng', // Pahawh Hmong
  Hmnp = 'Hmnp', // Nyiakeng Puachue Hmong
  Hrkt = 'Hrkt', // Japanese syllabaries (alias for Hiragana + Katakana)
  Hung = 'Hung', // Old Hungarian (Hungarian Runic)
  Inds = 'Inds', // Indus (Harappan)
  Ital = 'Ital', // Old Italic (Etruscan, Oscan, etc.)
  Jamo = 'Jamo', // Jamo (alias for Jamo subset of Hangul)
  Java = 'Java', // Javanese
  Jpan = 'Jpan', // Japanese (alias for Han + Hiragana + Katakana)
  Jurc = 'Jurc', // Jurchen
  Kali = 'Kali', // Kayah Li
  Kana = 'Kana', // Katakana
  Kawi = 'Kawi', // Kawi
  Khar = 'Khar', // Kharoshthi
  Khmr = 'Khmr', // Khmer
  Khoj = 'Khoj', // Khojki
  Kitl = 'Kitl', // Khitan large script
  Kits = 'Kits', // Khitan small script
  Knda = 'Knda', // Kannada
  Kore = 'Kore', // Korean (alias for Hangul + Han)
  Kpel = 'Kpel', // Kpelle
  Kthi = 'Kthi', // Kaithi
  Lana = 'Lana', // Tai Tham (Lanna)
  Laoo = 'Laoo', // Lao
  Latf = 'Latf', // Latin (Fraktur variant)
  Latg = 'Latg', // Latin (Gaelic variant)
  Latn = 'Latn', // Latin
  Leke = 'Leke', // Leke
  Lepc = 'Lepc', // Lepcha (Róng)
  Limb = 'Limb', // Limbu
  Lina = 'Lina', // Linear A
  Linb = 'Linb', // Linear B
  Lisu = 'Lisu', // Lisu (Fraser)
  Loma = 'Loma', // Loma
  Lyci = 'Lyci', // Lycian
  Lydi = 'Lydi', // Lydian
  Mahj = 'Mahj', // Mahajani
  Maka = 'Maka', // Makasar
  Mand = 'Mand', // Mandaic, Mandaean
  Mani = 'Mani', // Manichaean
  Marc = 'Marc', // Marchen
  Maya = 'Maya', // Mayan hieroglyphs
  Medf = 'Medf', // Medefaidrin (Oberi Okaime, Oberi Ɔkaimɛ)
  Mend = 'Mend', // Mende Kikakui
  Merc = 'Merc', // Meroitic Cursive
  Mero = 'Mero', // Meroitic Hieroglyphs
  Mlym = 'Mlym', // Malayalam
  Modi = 'Modi', // Modi, Moḍī
  Mong = 'Mong', // Mongolian
  Moon = 'Moon', // Moon (Moon code, Moon script, Moon type)
  Mroo = 'Mroo', // Mro, Mru
  Mtei = 'Mtei', // Meitei Mayek (Meithei, Meetei)
  Mult = 'Mult', // Multani
  Mymr = 'Mymr', // Myanmar (Burmese)
  Nagm = 'Nagm', // Nag Mundari
  Nand = 'Nand', // Nandinagari
  Narb = 'Narb', // Old North Arabian (Ancient North Arabian)
  Nbat = 'Nbat', // Nabatean
  Newa = 'Newa', // Newa, Newar, Newari, Nepāla lipi
  Nkgb = 'Nkgb', // Nakhi Geba (’Na-’Khi ²Ggŏ-¹baw, Naxi Geba)
  Nkoo = 'Nkoo', // N’Ko
  Nshu = 'Nshu', // Nüshu
  Ogam = 'Ogam', // Ogham
  Olck = 'Olck', // Ol Chiki (Ol Cemet’, Ol, Santali)
  Orkh = 'Orkh', // Old Turkic, Orkhon Runic
  Orya = 'Orya', // Oriya (Odia)
  Osge = 'Osge', // Osage
  Osma = 'Osma', // Osmanya
  Ougr = 'Ougr', // Old Uyghur
  Palm = 'Palm', // Palmyrene
  Pauc = 'Pauc', // Pau Cin Hau
  Perm = 'Perm', // Old Permic
  Phag = 'Phag', // Phags-pa
  Phli = 'Phli', // Inscriptional Pahlavi
  Phlp = 'Phlp', // Psalter Pahlavi
  Phlv = 'Phlv', // Book Pahlavi
  Phnx = 'Phnx', // Phoenician
  Piqd = 'Piqd', // Klingon (KLI plqaD)
  Plrd = 'Plrd', // Miao (Pollard)
  Prti = 'Prti', // Inscriptional Parthian
  Qaaa = 'Qaaa', // Reserved for private use (start)
  Qabp = 'Qabp', // Picture Communication Symbols (PCS)
  Qabw = 'Qabw', // Widgit symbols
  Qabx = 'Qabx', // Reserved for private use (end)
  Rjng = 'Rjng', // Rejang (Redjang, Kaganga)
  Roro = 'Roro', // Rongorongo
  Runr = 'Runr', // Runic
  Samr = 'Samr', // Samaritan
  Sara = 'Sara', // Sarati
  Sarb = 'Sarb', // Old South Arabian
  Saur = 'Saur', // Saurashtra
  Sgnw = 'Sgnw', // SignWriting
  Shaw = 'Shaw', // Shavian (Shaw)
  Shrd = 'Shrd', // Sharada, Śāradā
  Sidd = 'Sidd', // Siddham, Siddhaṃ, Siddhamātṛkā
  Sind = 'Sind', // Khudawadi, Sindhi
  Sinh = 'Sinh', // Sinhala
  Sogd = 'Sogd', // Sogdian
  Sogo = 'Sogo', // Old Sogdian
  Sora = 'Sora', // Sora Sompeng
  Soyo = 'Soyo', // Soyombo
  Sund = 'Sund', // Sundanese
  Sylo = 'Sylo', // Syloti Nagri
  Syrc = 'Syrc', // Syriac
  Syre = 'Syre', // Syriac (Estrangelo variant)
  Syrj = 'Syrj', // Syriac (Western variant)
  Syrn = 'Syrn', // Syriac (Eastern variant)
  Tagb = 'Tagb', // Tagbanwa
  Takr = 'Takr', // Takri, Ṭākrī, Ṭāṅkrī
  Tale = 'Tale', // Tai Le
  Talu = 'Talu', // New Tai Lue
  Taml = 'Taml', // Tamil
  Tang = 'Tang', // Tangut
  Tavt = 'Tavt', // Tai Viet
  Telu = 'Telu', // Telugu
  Teng = 'Teng', // Tengwar
  Tfng = 'Tfng', // Tifinagh (Berber)
  Tglg = 'Tglg', // Tagalog (Baybayin, Alibata)
  Thaa = 'Thaa', // Thaana
  Thai = 'Thai', // Thai
  Tibt = 'Tibt', // Tibetan
  Tirh = 'Tirh', // Tirhuta
  Tnsa = 'Tnsa', // Tangsa
  Toto = 'Toto', // Toto
  Ugar = 'Ugar', // Ugaritic
  Vaii = 'Vaii', // Vai
  Visp = 'Visp', // Visible Speech
  Vith = 'Vith', // Vithkuqi
  Wara = 'Wara', // Warang Citi (Varang Kshiti)
  Wcho = 'Wcho', // Wancho
  Wole = 'Wole', // Woleai
  Xpeo = 'Xpeo', // Old Persian
  Xsux = 'Xsux', // Cuneiform, Sumero-Akkadian
  Yezi = 'Yezi', // Yezidi
  Yiii = 'Yiii', // Yi
  Zanb = 'Zanb', // Zanabazar Square (Zanabazarin Dörböljin Useg, Xewtee Dörböljin Bicig, Horizontal Square Script)
  Zmth = 'Zmth', // Mathematical notation
  Zsye = 'Zsye', // Symbols (Emoji variant)
  Zsym = 'Zsym', // Symbols
  Zxxx = 'Zxxx', // Code for unwritten documents
  Zinh = 'Zinh', // Code for inherited script
  Zyyy = 'Zyyy', // Code for undetermined script
  Zzzz = 'Zzzz', // Code for uncoded script
}